version: '3.8'


networks:
  voice-net:
    driver: bridge

services:

  vosk-server:
    image: rhasspy/wyoming-vosk:latest
    container_name: vosk-server
    restart: unless-stopped
    ports:
      - "10300:10300"
    volumes:
      - ./vosk-data:/data
    command:
      - "--data-dir"
      - "/data"
      - "--language"
      - "en"
      - "--uri"
      - "tcp://0.0.0.0:10300"
      - "--debug"
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - voice-net

  openwakeword:
    image: rhasspy/wyoming-openwakeword:latest
    container_name: openwakeword
    restart: unless-stopped
    ports:
      - "10400:10400"
    entrypoint: ["/usr/src/.venv/bin/python3", "-m", "wyoming_openwakeword"]
    command:
      - "--uri"
      - "tcp://0.0.0.0:10400"
      - "--model"
      - "hey_jarvis"
    networks:
      - voice-net
